apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: d03jrppnd-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: d03jrppnd-python 
  name: d03jrppnd-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: d03jrppnd-python 
